// This file is automatically generated. Do not edit it directly.
import { createClient, SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Support both Vite (import.meta.env) and Next.js (process.env) environments
const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL || '';
const SUPABASE_PUBLISHABLE_KEY = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || '';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create a placeholder client for build time when env vars aren't available
const createSupabaseClient = (): SupabaseClient<Database> => {
  // During build time, env vars might not be available
  // Return a client that will work at runtime when env vars are present
  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    // Return a dummy client for static generation - it won't be used at runtime
    return createClient<Database>(
      'https://placeholder.supabase.co',
      'placeholder-key',
      {
        auth: {
          persistSession: false,
          autoRefreshToken: false,
        }
      }
    );
  }
  
  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
    }
  });
};

export const supabase = createSupabaseClient();